modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    modId="onlytinkeralmost"
    version="1.5.0"
    displayName="OnlyTinkerAlmost"
    authors="Xiaolang47y"
    description='''
Restricts the player to Tinkers' Construct (and addon) tools, weapons and armor.
Vanilla and other-mod equipment can only be used for crafting, unless whitelisted in config/onlytinkeralmost-common.toml.
'''

[[dependencies.onlytinkeralmost]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.onlytinkeralmost]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.onlytinkeralmost]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.9,)"
    ordering="NONE"
    side="BOTH"
